# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Foodies Application
on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "yarn.lock" ]; then
            echo "::set-output name=manager::yarn"
          elif [ -f "package-lock.json" ]; then
            echo "::set-output name=manager::npm"
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Initialize SQLite Database
        continue-on-error: true
        run: |
          # Replace with your script to initialize SQLite database
          npm run initdb

      - name: Archive artifact
        run: |
          tar czf artifact.tar.gz -C .next .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-nextjs-app
          path: artifact.tar.gz

  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-nextjs-app
          path: ./

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: .next
